name: Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 1 * *"
    - cron: "0 22 15 * *"

jobs:
  build:

    runs-on: ubuntu-20.04
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [22]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install repository dependencies
      if: ${{ success() }}
      run: npm install
    - name: Running Release Script
      if: ${{ success() }}
      run: npm run release
      env:
          VAULT_KEY: ${{ secrets.VAULT_KEY }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
    - name: Create new issue if release failed
      if: ${{ failure() }}
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Release failure",
          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}** because release failed."
          }'